#!/usr/bin/env bash

CACHE_FILE="/tmp/tmux_sessionizer_cache"

selected=$(find \
  ~/team-internet \
  ~/.config/nvim \
  ~/personal \
  ~/GolandProjects \
   -type d -not -path '*/node_modules/*' -exec test -e '{}/.git' ';' -print -prune | fzf
)

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(echo "$selected" | tr . _ | tr / - | sed 's/\(.\{64\}\).*/\1/')
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
